project:
  type: book
  output-dir: docs

book:
  title: "Chinaza Nnamdi Portfolio"
  chapters:
    - index.qmd
    - projects.qmd
    - part: "Machine Learning"
      chapters: 
        - machine_learning/background.qmd
    - part: "Single-Cell RNASeq"
      chapters:
        - single_cell_rnaseq/background.qmd
    - part: "Structural Variant Genotyping with a Pangenome"
      chapters: 
        - sv_genotyping/background.qmd
    - part: "Bulk RNASeq with a Pan-transcriptome"
      chapters: 
        - bulk_rnaseq_with_pantranscriptome/background.qmd
    - part: "Capstone Project for Computational Molecular Evolution Course"
      chapters: 
        - capstone_for_cmr_course/background.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

